### ISSUE TITLE
Подтверждение почты

### ISSUE THREAD

**Issue by Tomb-Raider** [Dostoyewski/PN_Expert#12]
Исправить страницу подтверждения
![image](https://user-images.githubusercontent.com/68435865/124396707-d570f900-dd13-11eb-936a-c6fb13185f57.png)
я тебе кидала исправленную страницу внеси её на сайт

**Comment by Dostoyewski** [comment]
Она уже там. Можешь ее еще раз кинуть?

**Comment by Dostoyewski** [comment]
@Tomb-Raider кстати, у тебя есть дотсуп к этому репу, так что можешь сама это сделать.
