### ISSUE TITLE
Статистика

### ISSUE THREAD

**Issue by Tomb-Raider** [Dostoyewski/PN_Expert#15]
1. Статистика тревоги и депрессии
один выход - возвращает балл тревоги и балл депрессии, т.е два числа
Эти числа результат прохождения теста 
![image](https://user-images.githubusercontent.com/68435865/124396596-2b916c80-dd13-11eb-8001-9bba0e8fe261.png)

2. Выоход с настроением - отдавать Коле число, полученное из опроса, чтобы он отображал настроение

**Comment by Dostoyewski** [comment]
@Tomb-Raider там же одно число, нет?

**Comment by Tomb-Raider** [comment]
У тревоги одно число, у депрессии другое число и у настроения 3е число @Dostoyewski
Это 3 разных опроса

**Comment by Tomb-Raider** [comment]
@Dostoyewski добавь выход для настроения, пожалуйста

**Comment by Tomb-Raider** [comment]
@Dostoyewski
