### ISSUE TITLE
Время лекарств на новый день

### ISSUE THREAD

**Issue by Tomb-Raider** [Dostoyewski/PN_Expert#16]
При наступлении нового дня время приёма лекарств не сбрасывается
![Screenshot_20210705_060431_io kodular gcherepennicov Parkinson](https://user-images.githubusercontent.com/68435865/124412543-6ddc9d00-dd57-11eb-96a3-54ac0cdb1a68.jpg)

**Comment by Dostoyewski** [comment]
@Tomb-Raider Тут прикол. Так как мы ушли от создания ивентов с таблетками, надо делать сброс со стороны фронта или приложухи.

**Comment by Dostoyewski** [comment]
Короче, есть выход для сброса времени, можно ли его кидать из приложения в полночь? Так мы сразу решим проблему с локальным временем.

**Comment by Dostoyewski** [comment]
Все равно Артур топит за приложение.

**Comment by Tomb-Raider** [comment]
@Dostoyewski не можем, потому что Гриша сможет сделать это в лучшем случае в августе, а нужно это сейчас. Поэтому надо думать другой вариант

**Comment by Tomb-Raider** [comment]
@Dostoyewski и все равно будут люди, которые пользуются платформой декстоп и там сброс не будет работать

**Comment by Tomb-Raider** [comment]
@Dostoyewski поменяй время сброса таблеток на 12 ночи пожалуйста

**Comment by Dostoyewski** [comment]
Поменял два дня назад, считаем issue закрытым.
