### ISSUE TITLE
`time_out` в `PillAssignedAdmin`

### ISSUE THREAD

**Issue by lunakoly** [Dostoyewski/PN_Expert#4]
Хотя в [`PillAssignedAdmin`](https://github.com/Dostoyewski/PN_Expert/blob/master/pills/admin.py#L17) есть `time_out`, в  админке его нет:

![изображение](https://user-images.githubusercontent.com/23314483/118355986-c70c2980-b57b-11eb-9299-7d096285af0c.png)

**Comment by Tomb-Raider** [comment]
пользователь назначает себе до какой даты принимать таблетки, но она автоматически сбрасывается до текущего дня @Dostoyewski

**Comment by Tomb-Raider** [comment]
не работает
![image](https://user-images.githubusercontent.com/68435865/122479088-35a53280-cfd3-11eb-9ab3-b246c1e2a690.png)

**Comment by Dostoyewski** [comment]
@Tomb-Raider это уже вопросы к фронту. У меня на локалке все работает.

**Comment by Dostoyewski** [comment]
И через выходы API работает тоже. Надо посмотреть, в каком формате @lunakoly отправляет данные.

**Comment by lunakoly** [comment]
@Tomb-Raider
У меня тоже все работает после фикса @Dostoyewski
